version: 2
updates:
- package-ecosystem: bundler
  target-branch: "main"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  target-branch: "main"
  directory: "/omnibus"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  target-branch: "4-stable"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  target-branch: "4-stable"
  directory: "/omnibus"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
