version: "2"
checks:
  file-lines:
    enabled: false
  identical-code:
    # Certain areas of the DSL are repetitive - like
    # lib/inspec/control_eval_context  - which requires
    # identical defs in both instance and class scope
    config:
      threshold: 20
plugins:
  fixme:
    enabled: true
    config:
      strings:
        - TODO
        - rubocop:disable
  flog:
    enabled: true
    score_threshold: 30.0
  markdownlint:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-49
    config:
      file: .rubocop.yml
