version: "2"
checks:
  file-lines:
    enabled: false
  identical-code:
    config:
      threshold: 40 # Unfortunately, we have a lot of duplicate code in places like lib/inspec/control_eval_context.rb
plugins:
  fixme:
    enabled: true
    config:
      strings:
        - TODO
        - rubocop:disable
  flog:
    enabled: true
    config:
      score_threshold: 30
  markdownlint:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-49
    config:
      file: .rubocop.yml
exclude_patterns:
  - "www/source/javascripts/"