branches:
  only:
    - master
    - 3-stable
    - /cw.*/
    - /mj.*/
    - /zenspider.*/
language: ruby
cache:
  - bundler
  - directories:
    - /home/travis/.rvm
dist: xenial
os:
  - linux
  - osx
services:
- docker
bundler_args: "--without integration tools maintenance deploy"
before_install:
- gem update --system
- gem --version
- bundle --version
env:
  - SLOW=1
  - CI_ENABLE_COVERAGE=true SLOW=1
matrix:
  fast_finish: true
  exclude:
  - os: osx
    env: CI_ENABLE_COVERAGE=true SLOW=1
  - os: linux
    env: SLOW=1
  include:
  - rvm: 2.6.3
  - rvm: 2.5.5
  - rvm: 2.4.5
  - script: bundle exec rake $SUITE
    bundler_args: "--without tools maintenance deploy"
    env: SUITE=test:integration[default-ubuntu-1604]
  - script: bundle exec rake $SUITE
    bundler_args: "--without tools maintenance deploy"
    env: SUITE=test:integration[default-ubuntu-1804]
  - script: bundle exec rake $SUITE
    bundler_args: "--without tools maintenance deploy"
    env: SUITE=test:integration[default-centos-6]
  - script: bundle exec rake $SUITE
    bundler_args: "--without tools maintenance deploy"
    env: SUITE=test:integration[default-centos-7]
  - script: bundle exec rake $SUITE
    bundler_args: "--without tools maintenance deploy"
    env: SUITE=test:integration[default-debian-8]
  - script: bundle exec rake $SUITE
    bundler_args: "--without tools maintenance deploy"
    env: SUITE=test:integration[default-debian-9]
  - script: bundle exec rake $SUITE
    bundler_args: "--without tools maintenance deploy"
    env: SUITE=test:integration[default-debian-10]
  - script: bundle exec rake $SUITE
    bundler_args: "--without tools maintenance deploy"
    env: SUITE=test:integration[default-oraclelinux-6]
  - script: bundle exec rake $SUITE
    bundler_args: "--without tools maintenance deploy"
    env: SUITE=test:integration[default-oraclelinux-7]
  - script: bundle exec rake $SUITE
    bundler_args: "--without tools maintenance deploy"
    env: SUITE=test:integration[default-fedora-29]

  allow_failures:
  - env: CI_ENABLE_COVERAGE=true SLOW=1
    script: bundle exec rake
