---
sudo: required
language: ruby
cache: bundler

# necessary for docker to work
dist: trusty
services:
  - docker

bundler_args: --without integration tools maintenance --with development

before_install:
  - gem install bundler
  - gem update --system 2.4.5
  - gem --version

matrix:
  include:
  - rvm: 1.9.3
  - rvm: 2.0
  - rvm: 2.2
    script: bundle exec rake lint test test:resources config=test/test.yaml
  - rvm: 2.2
    script: N=5 bundle exec rake test:functional test:resources config=test/test-extra.yaml
