branches:
  only:
    - master
    - /.*-stable/
    - /cw.*/
    - /mj.*/
    - /zenspider.*/
language: ruby
cache:
  bundler: true
  directories:
    - /home/travis/.rvm
dist: xenial
os:
  - linux
  - osx
services:
- docker
bundler_args: "--without tools maintenance deploy"
before_install:
- "gem update --system '3.0'"
- gem --version
- bundle --version
env:
  - SLOW=1 NO_AWS=1
  - CI_ENABLE_COVERAGE=true SLOW=1
script: bundle exec rake $SUITE
matrix:
  fast_finish: true
  exclude:
  - os: osx
    env: CI_ENABLE_COVERAGE=true SLOW=1
  - os: linux
    env: SLOW=1 NO_AWS=1
  include:
  - rvm: 2.6.3
  - rvm: 2.5.5
  - rvm: 2.4.5
  - env: SUITE=test:integration[default-ubuntu-1604]
  - env: SUITE=test:integration[default-ubuntu-1804]
  - env: SUITE=test:integration[default-centos-6]
  - env: SUITE=test:integration[default-centos-7]
  - env: SUITE=test:integration[default-debian-8]
  - env: SUITE=test:integration[default-debian-9]
  - env: SUITE=test:integration[default-debian-10]
  - env: SUITE=test:integration[default-oraclelinux-6]
  - env: SUITE=test:integration[default-oraclelinux-7]
  - env: SUITE=test:integration[default-fedora-29]
  allow_failures:
  - env: CI_ENABLE_COVERAGE=true SLOW=1
