os: Windows Server 2012 R2
platform:
  - x64

environment:
  bundler_url: https://rubygems.org/downloads/bundler-1.9.9.gem

  matrix:
    - ruby_version: "23"
    - ruby_version: "24"

clone_folder: c:\projects\inspec
clone_depth: 1
skip_tags: true
branches:
  only:
    - master

cache:
  - vendor/bundle -> appveyor.yml

install:
  - systeminfo
  - winrm quickconfig -q
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - ruby --version
  - gem --version
  - appveyor DownloadFile -Url %bundler_url% -FileName bundler.gem
  - gem install --local bundler --quiet --no-document
  - bundler --version
  - ruby -r rubygems -e "p Gem.path"

build_script:
  - bundle install --path=vendor/bundle --without integration tools maintenance deploy

test_script:
  - SET SPEC_OPTS=--format progress
  - bundle exec rake
