os: Windows Server 2012 R2
platform:
  - x64

environment:
  matrix:
    - ruby_version: "200-x64"
    - ruby_version: "21"

clone_folder: c:\projects\inspec
clone_depth: 1
skip_tags: true
branches:
  only:
    - master

install:
  - systeminfo
  - winrm quickconfig -q
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - ruby --version
  - gem install bundler --quiet --no-ri --no-rdoc
  - gem update --system 2.4.5
  - gem --version
  - bundler --version

build_script:
  - bundle install --without integration tools maintenance

test_script:
  - SET SPEC_OPTS=--format progress
  - bundle exec rake

cache:
  - C:/Ruby200-x64/bin/gem
  - C:/Ruby21/bin/gem
