os: Windows Server 2012 R2
platform:
  - x64

environment:
  matrix:
    - ruby_version: "23"
    - ruby_version: "24"
    - ruby_version: "25"
clone_folder: c:\projects\inspec
clone_depth: 1

skip_commits:
  # version bumps by Expeditor happen as a separate commit after the merge, we can skip
  author: Chef Expeditor
  # if ONLY the files listed below are changed in a commit, skip
  files:
    - '*.md'
    - docs/**/*
    - examples/**/*
    - MAINTAINERS.toml

skip_tags: true
branches:
  only:
    - master

cache:
  - vendor/bundle -> appveyor.yml

install:
  - systeminfo
  - winrm quickconfig -q
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - ruby --version
  - gem --version
  - bundler --version
  - ruby -r rubygems -e "p Gem.path"

build_script:
  - bundle install --path=vendor/bundle --without integration tools maintenance deploy
  - if not exist C:\tmp mkdir C:\tmp

test_script:
  - SET SPEC_OPTS=--format progress
  - bundle exec rake

for:
  -
    matrix:
      only:
        - ruby_version: "25"
    test_script:
      - SET SPEC_OPTS=--format progress
      - bundle exec rake
      - bundle exec rake test:functional:windows

