[Preamble]
  title = "Maintainers"
  text = """
This file lists how the InSpec project is maintained. When making changes to the
system, this file tells you who needs to review your patch - you need at least
two maintainers to provide a :+1: on your pull request. Additionally, you need
to not receive a veto from a Lieutenant or the Project Lead.
Check out [How Chef is Maintained](https://github.com/chef/chef-rfc/blob/master/rfc030-maintenance-policy.md#how-the-project-is-maintained)
for details on the process, how to become a maintainer, lieutenant, or the
project lead.
"""

[Org]
  [Org.Components]
     title = "Components"

     [Org.Components.InSpec]
        title = "InSpec"
        text = """
  Handles the [InSpec](https://github.com/chef/inspec) toolset.
  """
        team = "inspec-maintainers"

        lieutenant = "btm"

        maintainers = [
          "clintoncwolfe",
          "miah",
          "zenspyder"
        ]

[people]
  [people.btm]
    Name = "Bryan McLellan"
    GitHub = "btm"

  [people.clintoncwolfe]
    Name = "Clinton Wolfe"
    GitHub = "clintoncwolfe"

  [people.miah]
    Name = "Miah Johnson"
    GitHub = "miah"

  [people.zenspyder]
    Name = "Ryan Davis"
    GitHub = "zenspyder"

  [people.kekaichinose]
    Name = "Keka Ichinose"
    GitHub = "kekaichinose"
