---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: InSpec

platforms:
  - name: centos-7.1
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[prepare]
    attributes:
