# Documentation available at https://expeditor.chef.io/docs/getting-started/
---

product_key: inspec

rubygems:
 - inspec
 - inspec-core
 - inspec-bin:
    gemspec_path: ./inspec-bin/
 - inspec-core-bin:
    gemspec_path: ./inspec-bin/

docker_images:
 - inspec:
    build_args:
     - GEM_SOURCE: http://artifactory.chef.co/omnibus-gems-local

pipelines:
 - habitat/build
 - omnibus/release
 - omnibus/adhoc:
    definition: .expeditor/release.omnibus.yml
    env:
     - ADHOC: true
 - verify:
    description: Pull Request validation tests
    public: true
    env:
     - LANG: "C.UTF-8"
     - SLOW: 1
     - NO_AWS: 1
 - coverage:
    description: Generate test coverage report
    public: true
    env:
     - CI_ENABLE_COVERAGE: true
     - LANG: "C.UTF-8"
     - SLOW: 1
 - www/build:
    description: Build website.
    definition: .expeditor/wwwbuild.yml
 - www/deploy:
    description: Deploy website to inspec.io
    definition: .expeditor/wwwdeploy.yml
 - integration/libraries:
    description: Integration with plugins, gems, resource packs.
    definition: .expeditor/integration.libraries.yml
 - integration/profiles:
    description: Integration with compliance-profiles, and dev-sec
    definition: .expeditor/integration.profiles.yml
 - integration/cookbooks:
    description: Integration with the audit cookbook
    definition: .expeditor/integration.cookbooks.yml
 - integration/automate:
    description: Integration with Chef Automate
    definition: .expeditor/integration.automate.yml

schedules:
 - name: integration_schedule
   description: Periodic Integration Testing
   cronline: "0 8 * * *"

slack:
 notify_channel: inspec-notify

github:
 delete_branch_on_merge: true
 minor_bump_labels:
  - "Version: Bump Minor"
 version_tag_format: v{{version}}
 release_branch:
  - master:
     version_constraint: 4.*
  - 1-stable:
     version_constraint: 1.*
  - 2-stable:
     version_constraint: 2.*
  - 3-stable:
     version_constraint: 3.*

changelog:
 categories:
  - "Type: New Resource": "New Resources"
  - "Type: New Feature": "New Features"
  - "Type: Enhancement": "Enhancements"
  - "Type: Bug": "Bug Fixes"

merge_actions:
 - built_in:bump_version:
    ignore_labels:
     - "Version: Skip Bump"
     - "Expeditor: Skip All"
    only_if_modified:
     - docs/*
     - etc/*
     - habitat/*
     - inspec-bin/*
     - lib/*
     - omnibus/*
     - support/*
     - tasks/*
     - test/*
     - Gemfile*
     - LICENSE
     - "*.gemspec"
     - "*.md"
 - bash:.expeditor/update_version.sh:
    only_if: built_in:bump_version
 - built_in:update_changelog:
    ignore_labels:
     - "Changelog: Skip Update"
     - "Expeditor: Skip All"
 - trigger_pipeline:omnibus/release:
    ignore_labels:
     - "Omnibus: Skip Build"
     - "Expeditor: Skip All"
 - trigger_pipeline:habitat/build:
    ignore_labels:
     - "Habitat: Skip Build"
     - "Expeditor: Skip All"
 - built_in:build_gem:
    only_if:
     - built_in:bump_version

subscriptions:
 - workload: artifact_published:unstable:inspec:{{version_constraint}}
   actions:
    - built_in:build_docker_image
 - workload: artifact_published:current:inspec:{{version_constraint}}
   actions:
    - built_in:tag_docker_image
    - built_in:promote_habitat_packages
 - workload: artifact_published:stable:inspec:{{version_constraint}}
   actions:
    - bash:.expeditor/update_dockerfile.sh
    - built_in:rollover_changelog
    - built_in:publish_rubygems
    - built_in:create_github_release
    - built_in:tag_docker_image
    - built_in:promote_habitat_packages
    - bash:.expeditor/publish-release-notes.sh:
       post_commit: true
    - bash:.expeditor/purge-cdn.sh:
       post_commit: true
    - bash:.expeditor/announce-release.sh:
       post_commit: true
    - built_in:notify_chefio_slack_channels
 - workload: pull_request_opened:{{agent_id}}:*
   actions:
     - post_github_comment:.expeditor/templates/pull_request.mustache
